apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: wf01a7gnj-nodejs 
  janus-idp.io/tekton: wf01a7gnj-nodejs
  backstage.io/kubernetes-id: wf01a7gnj-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: wf01a7gnj-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml