apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: wf01a7gnj-nodejs
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-nodejs:6fa8c53bd4690c57063ed05129e3e7acab38996a@sha256:c4aa49436ed1e51198052c2cf8a9f0224fc87fd20944cd550cd935e58b836f94
          name: container-image
