apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: wf01a7gnj-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: wf01a7gnj-nodejs 
  name: wf01a7gnj-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: wf01a7gnj-nodejs 
